In [1]:
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt

# Import Sitka yearly temperature data

In [4]:
data = pd.read_csv('/Users/joseservin/Project_Data_Visualization/Chapter_16/sitka_weather_2014.csv')
data

,AKST,Max TemperatureF,Mean TemperatureF,Min TemperatureF,Max Dew PointF,MeanDew PointF,Min DewpointF,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityMiles,Mean VisibilityMiles,Min VisibilityMiles,Max Wind SpeedMPH,Mean Wind SpeedMPH,Max Gust SpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,2014-1-1,46,42,37,40,38,36,97,86,76,...,10,8,2,25,14,36.0,0.69,8,Rain,138
1,2014-1-2,41,38,35,38,35,32,97,89,76,...,10,9,4,14,7,22.0,0.34,8,Rain,92
2,2014-1-3,39,36,34,38,36,33,100,97,93,...,10,9,2,8,3,NaN,0.02,7,Rain,102
3,2014-1-4,43,38,34,35,33,31,97,82,62,...,10,10,10,20,6,25.0,0.00,6,Rain,107
4,2014-1-5,44,42,41,42,36,32,97,77,63,...,10,8,2,26,17,36.0,0.37,8,Rain,113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,2014-12-18,45,43,41,33,30,27,67,60,55,...,10,10,10,21,14,30.0,0.00,7,Rain,112
352,2014-12-19,46,44,42,35,33,30,74,65,60,...,10,10,10,21,15,31.0,0.01,6,Rain,117
353,2014-12-20,46,44,41,39,36,33,93,72,59,...,10,10,7,21,15,30.0,0.07,8,Rain,117
354,2014-12-21,42,40,37,40,38,37,100,94,85,...,10,10,9,10,6,NaN,0.11,7,Rain,85
355,2014-12-22,45,42,39,41,38,32,97,85,67,...,10,9,4,23,8,22.0,0.15,7,Rain,130

# Find average max temperature grouped by month

In [23]:
data.insert(1, 'Month', pd.DatetimeIndex(data['AKST']).month)

In [24]:
data

,AKST,Month,Max TemperatureF,Mean TemperatureF,Min TemperatureF,Max Dew PointF,MeanDew PointF,Min DewpointF,Max Humidity,Mean Humidity,...,Max VisibilityMiles,Mean VisibilityMiles,Min VisibilityMiles,Max Wind SpeedMPH,Mean Wind SpeedMPH,Max Gust SpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,2014-1-1,1,46,42,37,40,38,36,97,86,...,10,8,2,25,14,36.0,0.69,8,Rain,138
1,2014-1-2,1,41,38,35,38,35,32,97,89,...,10,9,4,14,7,22.0,0.34,8,Rain,92
2,2014-1-3,1,39,36,34,38,36,33,100,97,...,10,9,2,8,3,NaN,0.02,7,Rain,102
3,2014-1-4,1,43,38,34,35,33,31,97,82,...,10,10,10,20,6,25.0,0.00,6,Rain,107
4,2014-1-5,1,44,42,41,42,36,32,97,77,...,10,8,2,26,17,36.0,0.37,8,Rain,113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,2014-12-18,12,45,43,41,33,30,27,67,60,...,10,10,10,21,14,30.0,0.00,7,Rain,112
352,2014-12-19,12,46,44,42,35,33,30,74,65,...,10,10,10,21,15,31.0,0.01,6,Rain,117
353,2014-12-20,12,46,44,41,39,36,33,93,72,...,10,10,7,21,15,30.0,0.07,8,Rain,117
354,2014-12-21,12,42,40,37,40,38,37,100,94,...,10,10,9,10,6,NaN,0.11,7,Rain,85
355,2014-12-22,12,45,42,39,41,38,32,97,85,...,10,9,4,23,8,22.0,0.15,7,Rain,130

In [26]:
month_data = data.groupby(['Month']).mean()

In [28]:
month_data

,Max TemperatureF,Mean TemperatureF,Min TemperatureF,Max Dew PointF,MeanDew PointF,Min DewpointF,Max Humidity,Mean Humidity,Min Humidity,Max Sea Level PressureIn,...,Min Sea Level PressureIn,Max VisibilityMiles,Mean VisibilityMiles,Min VisibilityMiles,Max Wind SpeedMPH,Mean Wind SpeedMPH,Max Gust SpeedMPH,PrecipitationIn,CloudCover,WindDirDegrees
Month,,,,,,,,,,,,,,,,,,,,,
1,45.709677,41.903226,38.032258,40.451613,37.193548,33.709677,95.709677,84.419355,69.967742,30.058710,...,29.783871,10.0,8.483871,4.548387,17.322581,8.838710,30.055556,0.403226,6.290323,109.354839
2,37.107143,32.142857,27.000000,25.678571,20.857143,15.464286,82.750000,66.285714,49.178571,29.953214,...,29.736429,10.0,8.892857,6.714286,13.964286,7.000000,27.307692,0.061429,3.535714,112.250000
3,42.516129,37.290323,32.612903,29.483871,24.645161,19.935484,77.645161,63.580645,48.258065,29.943226,...,29.662903,10.0,9.322581,7.290323,16.838710,8.096774,26.800000,0.178710,4.806452,151.096774
4,47.700000,42.700000,38.133333,38.633333,35.566667,32.000000,90.500000,76.433333,60.000000,29.894333,...,29.655000,10.0,9.466667,7.166667,16.333333,7.733333,27.750000,0.128333,6.033333,201.133333
5,56.806452,51.290323,46.129032,44.774194,41.709677,38.032258,86.903226,73.290323,59.096774,30.105806,...,29.950000,10.0,9.612903,7.774194,13.677419,5.580645,23.222222,0.022581,5.225806,225.161290
6,57.400000,52.366667,48.266667,49.033333,46.700000,43.900000,93.333333,82.000000,67.066667,30.037333,...,29.885667,10.0,8.966667,5.766667,14.000000,6.033333,22.200000,0.191667,6.633333,222.600000
7,61.161290,56.870968,53.161290,54.548387,52.580645,50.322581,96.161290,86.774194,74.096774,30.077742,...,29.946452,10.0,8.645161,4.774194,12.096774,4.548387,25.833333,0.197742,7.032258,236.580645
8,62.677419,57.741935,53.387097,56.193548,53.967742,50.903226,97.516129,87.903226,74.741935,30.041290,...,29.910645,10.0,8.483871,4.677419,13.451613,5.935484,24.285714,0.432903,6.290323,195.129032
9,59.033333,54.600000,50.466667,53.833333,51.366667,47.833333,98.766667,89.700000,73.100000,29.967667,...,29.771000,10.0,8.400000,4.200000,13.900000,6.133333,30.166667,0.356000,7.066667,175.966667
10,50.870968,46.290323,41.935484,45.322581,41.741935,37.483871,95.612903,84.258065,66.967742,29.699355,...,29.419032,10.0,9.032258,5.741935,18.032258,8.935484,31.722222,0.326452,6.193548,102.000000
11,43.366667,39.033333,34.500000,38.166667,34.400000,29.866667,95.600000,85.366667,69.300000,30.022333,...,29.774333,10.0,9.066667,5.166667,14.100000,7.100000,30.083333,0.302333,5.066667,115.166667
12,44.363636,41.090909,37.818182,38.409091,35.772727,32.545455,91.136364,81.409091,69.090909,29.664545,...,29.370455,10.0,9.545455,7.045455,17.818182,10.000000,29.214286,0.193182,6.590909,107.863636

# Find month with highest and lowest max temp

In [34]:
month_data['Max TemperatureF'].idxmax()

8

In [35]:
month_data['Max TemperatureF'].idxmin()

2

# Create February data DF

# Create August data DF